### ISSUE TITLE
shouldMorph doesn't work well with some form elements

### ISSUE THREAD

**Issue by adank92** [hopsoft/cable_ready#70] opened 2020-09-07 21:24 UTC
First of all, I want to thank you for this awesome gem (and for Stimulus Reflex too). It has been fun using them!

I noticed that performing a full page morph is causing some issues with `select` and `input` tags. The first issue I ran into is that select tags that have a "blank" option selected are being cleared out even if their values are not changed. After some debugging I was able to connect these issues with the `shouldMorph` method.

I've created [this repo](https://github.com/adank92/cable_ready_form_element_issues/) to show the issues described here.

### First issue: select tags are cleared out

![select](https://user-images.githubusercontent.com/5948052/92415871-3b5f1500-f131-11ea-8bf0-e41d175578ca.gif)

**Code**
```
# app/views/tests/index.html.erb
<%= select_tag :foo, raw('<option>Test</option>'), prompt: 'Blank Option' %>
<%= select_tag :bar, raw('<option>Test</option>'), prompt: 'Blank Option', data: { reflex: 'change->test#change' } %>
```
```
# app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
  end
end
```
```
# app/reflexes/test_reflex.rb
class TestReflex < ApplicationReflex
  def change
  end
end
```
**This is what morphdom does if we don't use `shouldMorph` at all:**

```
// This line gets called at some point, sending the current blank option and the blank option
// from the backend, which are the same
syncBooleanAttrProp(fromEl, toEl, "selected");
```
[source](https://github.com/patrick-steele-idem/morphdom/blob/master/src/specialElHandlers.js#L35)
```
// This method will set the "selected" to the blank option
function syncBooleanAttrProp(fromEl, toEl, name) {
  if (fromEl[name] !== toEl[name]) {
    fromEl[name] = toEl[name];
    if (fromEl[name]) {
      fromEl.setAttribute(name, "");
    } else {
      fromEl.removeAttribute(name);
    }
  }
}
```
[source](https://github.com/patrick-steele-idem/morphdom/blob/master/src/specialElHandlers.js#L1)
```
// Later on this method is called to morph the select input
SELECT: function (fromEl, toEl) {
    if (!toEl.hasAttribute("multiple")) {
      var selectedIndex = -1;
[...]
          if (nodeName === "OPTION") {

            // There's a child with selected here! It will change selectedIndex from -1 to 0

            if (curChild.hasAttribute("selected")) {
              selectedIndex = i;
              break;
            }
            i++;
          }
[...]
      // This works just fine because there's an option that has the "selected" attribute!
      // fromEl.selectedIndex = 0
      // selectedIndex = 0

      fromEl.selectedIndex = selectedIndex;
    }
}
```
[source](https://github.com/patrick-steele-idem/morphdom/blob/master/src/specialElHandlers.js#L75-L107)

**Now this is what happens if we use `shouldMorph` from cable_ready:**
```
var shouldMorph = function shouldMorph(permanentAttributeName) {
  return function (fromEl, toEl) {

    // current blank option is equal to the blank option from the backend, so the option is not morphed

    if (fromEl.isEqualNode(toEl)) return false;
```
[source](https://github.com/hopsoft/cable_ready/blob/master/javascript/cable_ready.js#L81-L100)
```
// This gets called eventually
SELECT: function SELECT(fromEl, toEl) {
    if (!toEl.hasAttribute('multiple')) {
      var selectedIndex = -1;
[...]
          if (nodeName === 'OPTION') {

            // We don't have any child option with the "SELECTED" attribute set, so this never gets executed

            if (curChild.hasAttribute('selected')) {
              selectedIndex = i;
              break;
            }
[...]
      // This deselects the blank option because it didn't find any 'selected' option
      // fromEl.selectedIndex = 0
      // selectedIndex = -1

      fromEl.selectedIndex = selectedIndex;
    }
  }
```
[source](https://github.com/patrick-steele-idem/morphdom/blob/master/src/specialElHandlers.js#L75-L107)

### Second issue: Input stays with the same value

This issue is similar to the one explained above, so I'm going to skip the details. This input is not being cleared out because `shouldMorph` returns false.

![input](https://user-images.githubusercontent.com/5948052/92416581-95150e80-f134-11ea-85a9-b8f54ce40214.gif)

**Code**
```
# app/views/tests/index.html.erb
<%= select_tag :foo, raw('<option>Test</option>'), prompt: 'Blank Option', data: { reflex: 'change->test#change' } %>
<%= text_field_tag :baz, @baz %>
```
```
# app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @baz = ""
  end
end
```
```
# app/reflexes/test_reflex.rb
class TestReflex < ApplicationReflex
  def change
  end
end
```

I think these issues might be part of the reason why LiveView is not using `isEqualNode`, as @snewcomer mentioned [here](https://github.com/patrick-steele-idem/morphdom/issues/153#issuecomment-590694559).

**Comment by leastbad** [comment] 2020-09-07 21:37
We can talk more about the select issue, but let's address the input first.

1. Those helpers generate `id` attributes, right? If not, throw some id's on those elements.
2. It's hard to tell from the animation, but you're sure that [single source of truth](https://docs.stimulusreflex.com/working-with-forms#single-source-of-truth) isn't *helping* you?

**Comment by adank92** [comment] 2020-09-07 22:01
@leastbad Thanks for the fast reply.
1. Yeah, those helpers generate ids: 
```
<select name="foo" id="foo" data-reflex="change->test#change" data-controller="stimulus-reflex" data-action="change->stimulus-reflex#__perform">
  <option value="">Blank Option</option>
  <option>Test</option>
</select>
<input type="text" name="baz" id="baz" value="">
```
2. I think it's not. What I'm expecting is that changing the value of the `<select>` input clears out the `<input>`. I've encountered this issue when trying to implement a button that resets all the inputs inside a form. Clearing all the session values in the backend (or simply assigning the instance variables to nil) is not clearing the inputs. I have an implementation similar to [tabular](https://expo.stimulusreflex.com/demos/tabular) but that also has a button that removes all the filters.

**Comment by leastbad** [comment] 2020-09-07 22:54
It would certainly help if you could throw up a quick MVCE. Feel free to use https://github.com/leastbad/stimulus_reflex_harness as a starting point.

So freaking weird!

**Comment by adank92** [comment] 2020-09-08 01:00
@leastbad Sure thing, [here it is](https://github.com/adank92/stimulus_reflex_harness). If you leave the blank option selected for the select tag and write some text in the input, clicking the button will wipe out the select input and will keep the input untouched. The expected behavior should the opposite of that (wipe out the input as the controller is blanking it and leave the select tag untouched)

**Comment by leastbad** [comment] 2020-09-08 01:16
Thank you so much for doing this, Adan.

I have to sleep soon but I'll clone your repo tomorrow morning.

**Comment by leastbad** [comment] 2020-09-08 13:44
Alright, Adan, I was able to get your MVCE up and verified that the behaviour you're seeing is happening on my computer as well, regardless of how weird it would be to have a select with two different blank options. After all, it's not the text label of the option but the (missing) value attribute that matters, in this case.

Having had a chance to sleep on this, I'm feeling a bit grumpy about the issue even though I know you're being super helpful.

The reason is that the first issue (really, they are both the same issue) makes a case for there being undesired behaviour, but stops short of actually saying what you want **us** to do about it.

Are you saying that we should pull out our shouldMorph functionality? This would mean giving up the ability to mark sections as permanent and protect active input elements from being overwritten by the server while you're typing into it. *That's not an even remotely acceptable outcome.*

Otherwise, you've clearly done enough forensic research to understand exactly why this is happening and you already understand that the issue is clearly something that only the morphdom library itself could fix.

So yeah, it's frustrating that these sorts of edge cases require workarounds and special consideration. However, it seems like the issue should be filed with morphdom, not CableReady. Am I wildly off-mark here?

**Comment by adank92** [comment] 2020-09-08 14:20
@leastbad 
> regardless of how weird it would be to have a select with two different blank options

In the MVCE I created there are two blank options but the same issue happens even if you have just one blank option, which is very common. I've updated my repo to show [this](https://github.com/adank92/stimulus_reflex_harness/commit/535014b54f8d90fcd6c52423f65cbe4674b46480).

> Having had a chance to sleep on this, I'm feeling a bit grumpy about the issue even though I know you're being super helpful.

Actually, I was preparing a PR with a proposal but since you replied so quickly I wanted to wait to see if I was missing something or if you wanted to take a different route.

>The reason is that the first issue (really, they are both the same issue) makes a case for there being undesired behaviour, but stops short of actually saying what you want us to do about it.

>Are you saying that we should pull out our shouldMorph functionality? This would mean giving up the ability to mark sections as permanent and protect active input elements from being overwritten by the server while you're typing into it. That's not an even remotely acceptable outcome.

I don't think we should remove shouldMorph, I think we should remove `if (fromEl.isEqualNode(toEl)) return false` from that method.

I mentioned it in my original description: 
> I think these issues might be part of the reason why LiveView is not using isEqualNode, as @snewcomer mentioned [here](https://github.com/patrick-steele-idem/morphdom/issues/153#issuecomment-590694559).

Even morphdom's documentation mentions that `isEqualNode` is not used in the core lib yet [due to very minor concerns](https://github.com/patrick-steele-idem/morphdom#can-i-make-morphdom-blaze-through-the-dom-tree-even-faster-yes).

I'll create a PR with this proposal.

**Comment by leastbad** [comment] 2020-09-08 14:31
Ahh, that makes a lot more sense. :)

Thanks for explaining.

Okay! I'll get the team to take a good look at this. Seems like the right thing to do, but testing is required.

**Comment by adank92** [comment] 2020-09-08 14:34
Awesome! Sorry for the confusion, I should have created the PR right away at least to show what I was thinking of.

Thank you for your time!

**Comment by leastbad** [comment] 2020-09-18 07:33
Just to keep you up to date: I am excited to get this merged but we're dealing with some IRL stresses that are slowing down things.

#71 has not been forgotten.

**Comment by adank92** [comment] 2020-09-18 14:29
That's completely understandable, take your time!

**Comment by leastbad** [comment] 2020-11-10 11:38
Time sure flies. Looking at this with fresh eyes, I'm feeling pretty confident that this is a positive step.

We are getting ready to push out the next version and I'd like this to be part of what we're testing.

**Closed by leastbad** 2020-11-10 11:39 UTC

**Comment by leastbad** [comment] 2020-11-16 02:26
Before I forget... you might find it useful in the future to know that if you specify `data-reflex="change"` (eg. just the event to capture) it will run a default application reflex action that just serves to refresh the page. No need to actually define an TestReflex with an empty action.

**Comment by adank92** [comment] 2020-11-16 14:39
Awesome, thanks for the tip!
